### PR TITLE
Adds the images in game notes

### PR DESCRIPTION
**Pull request by beelee1**
I copied what the yaml PR #8966 had for description. I think it should work but not 100% sure. @DanVanAtta so when you get time I think this is all that's needed and then have the #8966 fixed and it should be ready to roll. I know @merleyn is excited to share the fruits of his labor :)

Thanks

Edit
I think the "Main" branch should be deleted. Everything needed is in Master.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Thanks for picking this up @beelee1 

I think the images need to go in a 'doc/images' folder to be picked up. Are you sure about where these files are added @beelee1 ?

**Comment by beelee1** [comment]
@DanVanAtta yea so these are already in the doc/images. I just went through the xml to see which ones were in Game Notes.

**Comment by DanVanAtta** [comment]
Cool - though, please correct me if I'm wrong, the game notes pull their images from 'doc/images'. So I'm confused why these are needed at the top level?

**Comment by DanVanAtta** [comment]
It appearsthe images are rendering in game notes:

Screenshot from 2021-03-04 21-04-00

**Comment by beelee1** [comment]
yea so I thought after preview.png was added all images in Game Notes had to be added where map README and description.html are. This is what I have for G 40 HRs

Screenshot from 2021-03-04 23-28-10

The "Neutral_Navy" is in the Game Notes. Perhaps I've misunderstood this the whole time lol

I guess this is where I got mixed up
https://forums.triplea-game.org/topic/2603/standard-preview-png-image?_=1614922348134 

"...if an image is in a 'doc/images' folder then it is likely also used in game notes. In this case we need to copy the existing thumbnail..."

**Comment by beelee1** [comment]
I'm guessing this can be closed or should i get rid or the images and leave the description ? Also a DL error. Probably a naming issue.
Screenshot from 2021-03-04 23-44-00

I guess I'll reopen the yaml and post it there ? I'll look at his xml now see if I can find it

edit
hmm...maybe this is on my end.

**Comment by beelee1** [comment]
@DanVanAtta yea so idk whats up. His naming looks correct. The first one doesn't matter if I remember right and the second one is the same

Screenshot from 2021-03-05 00-02-11

Screenshot from 2021-03-05 00-03-37

**Comment by beelee1** [comment]
Sorry to spam out here but when you DL the map it shows up as

Screenshot from 2021-03-05 00-12-12
It doesn't have the "1st Edition" and then when you go to select maps it has

Screenshot from 2021-03-05 00-16-51
which is his name at the beginning of the xml, which is correct I believe. The first one doesn't seem right though.

**Comment by beelee1** [comment]
edit 
so the zip is named "ww2_oil_and_snow-master" and when you open it the first folder is "ww_2_oil_and_snow_1st_edition"  I tried matching them up both ways but still got the error. 

At any rate, sure you can fix it or tell me how :)

**Comment by beelee1** [comment]
Uggh ... OK @DanVanAtta  I tried renaming the zip to 1st_edition again and it worked. Game starts and runs. Still not sure how or what I need to do to fix it though. At any rate that is/was the problem

**Pull request closed without merging**
